# Generated by Django 4.1.5 on 2023-02-10 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Health', '0002_predict'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='predict',
            name='semester',
        ),
        migrations.AddField(
            model_name='predict',
            name='Cough',
            field=models.CharField(choices=[('1', 'Yes'), ('0', 'No')], default='0', max_length=20),
        ),
    ]
