# Generated by Django 4.1.5 on 2023-02-10 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Health', '0003_remove_predict_semester_predict_cough'),
    ]

    operations = [
        migrations.AddField(
            model_name='predict',
            name='Are_You_Above_60',
            field=models.CharField(choices=[('1', 'Yes'), ('0', 'No')], default='0', max_length=20),
        ),
        migrations.AddField(
            model_name='predict',
            name='Fever',
            field=models.CharField(choices=[('1', 'Yes'), ('0', 'No')], default='0', max_length=20),
        ),
        migrations.AddField(
            model_name='predict',
            name='Gender',
            field=models.CharField(choices=[('1', 'Male'), ('0', 'Female')], default='0', max_length=20),
        ),
        migrations.AddField(
            model_name='predict',
            name='Sore_Throat',
            field=models.CharField(choices=[('1', 'Yes'), ('0', 'No')], default='0', max_length=20),
        ),
        migrations.AddField(
            model_name='predict',
            name='head_ache',
            field=models.CharField(choices=[('1', 'Yes'), ('0', 'No')], default='0', max_length=20),
        ),
        migrations.AddField(
            model_name='predict',
            name='shortness_of_breath',
            field=models.CharField(choices=[('1', 'Yes'), ('0', 'No')], default='0', max_length=20),
        ),
        migrations.AddField(
            model_name='predict',
            name='test_indication',
            field=models.CharField(choices=[('0', 'other'), ('1', 'Contact with confirmed'), ('2', 'Abroad')], default='0', max_length=20),
        ),
    ]
